echo "Building..."
export MACOSX_DEPLOYMENT_TARGET=10.9

mkdir -p build/xcode/Build/Products/Debug
mkdir -p build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/Objects-normal/x86_64

#swift -target x86_64-apple-macosx10.9 -module-name Taylor -O0 -sdk /Applications/Xcode6-Beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -g -module-cache-path /Library/Developer/Xcode/DerivedData/ModuleCache -I build/xcode/Build/Products/Debug -F build/xcode/Build/Products/Debug -c -j4 main.swift taylor/taylor.swift taylor/request.swift taylor/response.swift taylor/route.swift taylor/router.swift -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/Objects-normal/x86_64/CLITaylor.swiftmodule -Xcc -iquote -Xcc build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/CLITaylor-generated-files.hmap -Xcc -Ibuild/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/CLITaylor-own-target-headers.hmap -Xcc -Ibuild/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/CLITaylor-all-target-headers.hmap -Xcc -iquote -Xcc build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/CLITaylor-project-headers.hmap -Xcc -Ibuild/xcode/Build/Products/Debug/include -Xcc -I/Applications/Xcode6-Beta2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -Xcc -Ibuild/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/DerivedSources/x86_64 -Xcc -Ibuild/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/DerivedSources -Xcc -DDEBUG=1 -emit-objc-header -emit-objc-header-path build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/Objects-normal/x86_64/CLITaylor-Swift.h -import-objc-header taylor/bridge.h

swift -target x86_64-apple-macosx10.9 -module-name Taylor -c -j4 main.swift taylor/taylor.swift taylor/router.swift taylor/route.swift taylor/request.swift taylor/response.swift -emit-objc-header -emit-objc-header-path build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/Objects-normal/x86_64/CLITaylor-Swift.h -import-objc-header taylor/bridge.h -target x86_64-apple-macosx10.9  -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path build/Taylor.swiftmodule
/Applications/Xcode6-Beta2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/izqui/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode6-Beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.9 -g -Wno-sign-conversion -iquote build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/CLITaylor-generated-files.hmap -Ibuild/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/CLITaylor-own-target-headers.hmap -Ibuild/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/CLITaylor-all-target-headers.hmap -iquote build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/CLITaylor-project-headers.hmap -Ibuild/xcode/Build/Products/Debug/include -I/Applications/Xcode6-Beta2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -Ibuild/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/DerivedSources/x86_64 -Ibuild/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/DerivedSources -Fbuild/xcode/Build/Products/Debug -MMD -MT dependencies -MF build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/Objects-normal/x86_64/GCDAsyncSocket.d --serialize-diagnostics build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/Objects-normal/x86_64/GCDAsyncSocket.dia -c taylor/GCDAsyncSocket.m -o build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/Objects-normal/x86_64/GCDAsyncSocket.o

/Applications/Xcode6-Beta2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode6-Beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -Lbuild/xcode/Build/Products/Debug -Fbuild/xcode/Build/Products/Debug -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -rpath -Xlinker @loader_path/../Frameworks -mmacosx-version-min=10.9 -lswift_stdlib_core -L/Applications/Xcode6-Beta2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -Xlinker -rpath -Xlinker /Applications/Xcode6-Beta2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -Xlinker -force_load -Xlinker /Applications/Xcode6-Beta2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a -Xlinker -sectalign -Xlinker __SWIFT -Xlinker __ast -Xlinker 4 -Xlinker -sectcreate -Xlinker __SWIFT -Xlinker __ast -Xlinker build/Taylor.swiftmodule -fobjc-arc -fobjc-link-runtime -o taylor-binary
#clang -o app -c build/xcode/Build/Intermediates/CLITaylor.build/Debug/CLITaylor.build/Objects-normal/x86_64/GCDAsyncSocket.o build/Taylor.swiftmodule